apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.redirect.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  DB_HOST: {{ .Values.redirect.database.host | quote }}
  DB_PORT: {{ .Values.redirect.database.port | quote }}
  DB_NAME: {{ .Values.redirect.database.name | quote }}
  DB_SSLMODE: {{ .Values.redirect.database.sslMode | quote }}
