{{- if .Values.redirect.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.redirect.serviceAccountName" . }}
  labels:
    {{- include "app.redirect.labels" . | nindent 4 }}
  {{- with .Values.redirect.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.redirect.serviceAccount.automount }}
{{- end }}
